# Generated by Django 4.0.4 on 2022-04-21 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('descriotion', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatheringEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gathering.gathering')),
            ],
        ),
    ]
