# Generated by Django 4.0.4 on 2022-05-28 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gathering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringrequest',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='From', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatheringrequest',
            name='gathering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gathering.gathering'),
        ),
        migrations.AddField(
            model_name='gatheringrequest',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatheringentities',
            name='entities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatheringentities',
            name='gathering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gathering.gathering'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
