# Generated by Django 4.0.4 on 2022-05-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gathering', '0003_alter_gathering_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatheringentities',
            name='entities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatheringentities',
            name='gathering',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gathering.gathering'),
        ),
        migrations.AlterField(
            model_name='gatheringrequest',
            name='From',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='From', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatheringrequest',
            name='gathering',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gathering.gathering'),
        ),
        migrations.AlterField(
            model_name='gatheringrequest',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
    ]
