# Generated by Django 4.0.4 on 2022-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('evaluation', models.CharField(max_length=50)),
            ],
        ),
    ]
