# Generated by Django 4.0.4 on 2022-04-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('department', '0002_remove_department_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjetc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPretinence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subjetc')),
            ],
        ),
    ]
