# Generated by Django 4.0.4 on 2022-04-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjetc',
            new_name='Subject',
        ),
    ]
