# Generated by Django 4.0.4 on 2022-05-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('branch', '0002_alter_branch_department'),
        ('user', '0003_alter_branchrepresentative_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpertinence',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='userpertinence',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
