# Generated by Django 4.0.4 on 2022-04-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('us', 'user'), ('st', 'student'), ('te', 'teacher'), ('ad', 'admin'), ('su', 'superuser')], default='st', max_length=2),
        ),
    ]
