# Generated by Django 4.0.4 on 2022-04-23 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('user', '0006_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='premition_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('st', 'student'), ('te', 'teacher'), ('ad', 'admin'), ('su', 'superuser')], default='st', max_length=2),
        ),
        migrations.CreateModel(
            name='HOB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchRepresentative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
