# Generated by Django 4.0.4 on 2022-04-24 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_description_and_more'),
        ('user', '0008_alter_myuser_premition_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='premition_level',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.AddField(
            model_name='userpertinence',
            name='role',
            field=models.CharField(choices=[('st', 'student'), ('br', 'branchRepresentative'), ('te', 'teacher'), ('hob', 'headOfBranch'), ('hod', 'headOfDepartment'), ('ad', 'admin'), ('su', 'superuser')], default='st', max_length=3),
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
