# Generated by Django 4.0.4 on 2022-04-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_description_and_more'),
        ('branch', '0001_initial'),
        ('user', '0009_remove_myuser_premition_level_remove_myuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpertinence',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='userpertinence',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
