# Generated by Django 4.0.4 on 2022-04-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
        ),
    ]
