# Generated by Django 4.0.4 on 2022-04-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
