# Generated by Django 4.0.4 on 2022-04-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
